Completed Protected Index
Code-Empire-Devs/UNCHARTED pull request #12
Opened 2022-08-19 23:15 UTC by scharlez

2022-08-21 00:28 UTC, elysemontano requested changes
Please fix indentation where I left comments.

2022-08-21 00:28 UTC, elysemontano commented on app/javascript/components/App.js
> +						/>
The indentation looks a little off here.

2022-08-21 00:28 UTC, elysemontano commented on app/javascript/components/App.js
> +						}}/>
The indentation looks a little off here as well.

2022-08-21 00:28 UTC, elysemontano commented on app/javascript/components/pages/TripIndex.js
> +}
Check indentation

2022-08-22 18:31 UTC, scharlez commented
Please review revisions.

2022-08-22 19:55 UTC, elysemontano requested changes
Indentation looks a little off still on App.js and TripIndex.  Check that the page has tab spacing set to 2 or 4 then format the page.

2022-08-22 21:31 UTC, triciasykes requested changes
Trip Index is fine,  but now App.js is off

2022-08-22 21:42 UTC, triciasykes approved these changes

2022-08-22 21:43 UTC, elysemontano approved these changes

2022-08-22 21:54 UTC, merged